#!/bin/bash

username=$USER
bot_folder=$PWD/develop-helper-bot
server_folder=$PWD/server

install_dep () {
    python3 -m venv .venv
    source ./.venv/bin/activate
    python3 -m pip install .
    deactivate
}

cd $bot_folder
install_dep
cd ..

cd $server_folder
install_dep
cd ..

echo "[Unit]
Description=develop_server bot
After=multi-user.target

[Service]
Type=simple
User=$username
ExecStart=$server_folder/.venv/bin/python $server_folder/src/__main__.py

[Install]
WantedBy=multi-user.target
" | sudo tee /etc/systemd/system/develop_server.server.service

echo "[Unit]
Description=develop_server server
After=multi-user.target

[Service]
Type=simple
User=$username
ExecStart=$bot_folder/.venv/bin/python $bot_folder/bot/__main__.py

[Install]
WantedBy=multi-user.target
" | sudo tee /etc/systemd/system/develop_server.bot.service


sudo systemctl daemon-reload    

sudo systemctl enable develop_server.bot.service
sudo systemctl start develop_server.bot.service
  
sudo systemctl enable develop_server.server.service
sudo systemctl start develop_server.server.service